# Generated by Django 6.1 on 2026-08-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='after_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/after/'),
        ),
        migrations.AddField(
            model_name='project',
            name='before_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/before/'),
        ),
    ]
