# Generated by Django 6.1 on 2026-08-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_after_image_project_before_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorMakeover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Real Interior Makeover', max_length=200)),
                ('before_image', models.ImageField(upload_to='makeover/before/')),
                ('after_image', models.ImageField(upload_to='makeover/after/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='after_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='before_image',
        ),
    ]
